### ISSUE TITLE
face_code bei persons

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTDatabaseEditor#10]
Aktuell lässt sich der face_code einer Person an drei verschiedenen Stellen definieren.
Direkt als property im person-Tag, im images-Knoten und im data-Knoten.

In den meisten vorhandenen Fällen ist der images-Knoten einfach leer. Mein Vorschlag wäre, den face_code nur noch als direktes person-property zu unterstützen. Es wird ohnehin nur in seltenen Einzelfällen verwendet.

**Comment by GWRon** [comment]
Images kann denke ich "weg". Das war initial eingefuehrt worden um Bilder von Personen zu ermoeglichen (und auch Bilder von Filmen ... etc)

**Comment by GWRon** [comment]
Ob das dann als Property oder tag umgesetzt wird - das war nur fuer die "Uebersichtlichkeit" manchmal anders geloest - Notwendigen gibt es keine. Vor allem nicht mit einem Editor. 
```
<person face_code="xyz">
  <data>
    <face_code>xyz</face_code>
  </data>
</person>
```

**Comment by nittka** [comment]
Dann würde ich das gerne in der Dokumentation und in meinem Editor auf eine Möglichkeit für die face_code reduzieren.

**Comment by nittka** [comment]
Nach Diskussion face_code in regulären Personeneigenschaften (insignificant) und in Details (celebrity).
