### ISSUE TITLE
gender bei Personen

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTDatabaseEditor#11]
Es gibt *erstaunlich* viele Einträge, bei denen gender nicht definiert ist. Wie ist denn der Default-Wert von bookable (das heißt doch, dass man die Person im Supermarkt buchen kann, oder?), denn wann immer der Wert definiert ist ist er 0.
Wie also werden die Personen dann für den Supermarkt ausgewählt und dann einem Geschlecht zugeordnet!?
Vielleicht ist hier ja ein Grund, warum es vergleichsweise wenige Darsteller etc. gibt.

**Comment by GWRon** [comment]
```
	' can this person _theoretically_ be casted for a production, talkshow guests...
	' (this allows disabling show-guests like "the queen" - which might
	' be guest in an older show)
	Const CASTABLE:Int = 8			'4
	' can this person booked _now_ (eg temporarily not available)
	Const BOOKABLE:Int = 16			'5
```

Personen-Defaults sind wohl:
```
	Method New()
		'by default they can level up
		SetFlag(TVTPersonFlag.ACTIVE)
		SetFlag(TVTPersonFlag.BOOKABLE)
		SetFlag(TVTPersonFlag.CASTABLE)
		SetFlag(TVTPersonFlag.CAN_LEVEL_UP)
	End Method
```

IsBookable() wird als Fallback genutzt. Es sollte also, wenn "bookable" nicht im XML-Teil angegeben ist, "true" als Standardwert eingesetzt sein.

Wenn er also auf "0" definiert wird, soll diese Person - nicht fuer die Eigenproduktion verfuegbar sein. Im Gegensatz zu "CASTABLE" dient der Flag auch zur Auszeichnung einer "temporaeren Nichtverfuegbarkeit" (Krank, Auszeit, ...)

**Comment by GWRon** [comment]
CASTABLE ist also die absolute Eigenschaft ueberhaupt fuer Eigenproduktionen bereitzustehen - und BOOKABLE den temporaeren Zustand (der kann CASTABLE nur "abschalten" aber nicht "zuschalten")

**Comment by nittka** [comment]
Bei den Defaults wären also erstmal alle in der DB vorhandenen celebritypersons für eine Eigenproduktion verfügbar, oder (castable kann gar nicht gesetzt und bookable wird nur in einer Handvoll von Fällen auf 0 gesetzt)?
Dennoch ist die Auswahl ziemlich klein - liegt das an den nicht vergebenen Jobs oder dem nicht definierten Geschlecht? Es gibt ja die aus meiner Sicht durchaus berechtigte Beschwerde, dass die Auswahl ziemlich eingeschränkt ist.

**Comment by GWRon** [comment]
Alle "non-fictional" sind per se nicht ein Eigenproduktionen verwendbar.
Alle anderen "celebs" sollten buchbar sein - mit Ausnahmen von "bookable = 0" etc.

Viele Personen in der DB sind aber "insignificants" - also "Normalos" und die sind dann hinter dem "Amateur"-Eintrag versteckt.

**Comment by nittka** [comment]
Wie es aussieht, gibt es viel zu wenige nicht fiktionale Hauptpersonen! ...

**Comment by GWRon** [comment]
Dann muessen wir beim Spielstart einfach noch die Erstellung von fiktionalen Promis einbinden. Also so, dass fuer jeden Beruf mindestens X Maenner und Y Frauen verfuegbar sind.

**Comment by nittka** [comment]
Ich hatte erst überlegt, dass man doch einfach genügend Hauptpersonen definieren könnte, aber tatsächlich gefällt mir das zufällige Auffüllen besser. Es gibt dazu ja ohnehin noch ein TVTower-Ticket. Das werde ich mal entsprechend kommentieren.

**Comment by GWRon** [comment]
Meine Mail ging wohl unter:
>Das "Zufaellige Auffuellen" - derzeit bevorzugen ja die "Produzenten" Personen aus dem Spielland.
>Dies koennte beim Auffuellen auch gemacht werden - also hier, vorrangig Deutsch"namige" Personen generieren. 


Wuerden 2+2 (m/w) pro Job reichen?
Den Rest koennte man ja (zwangsweise) per Amateur-Auswahl rekrutieren.

**Comment by GWRon** [comment]
Siehe aktuelle Commits. 3+3 pro Job werden angelegt.
