### ISSUE TITLE
Variablenauflösung

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTDatabaseEditor#12]
Ich fange gerade mit ein paar Validierungen an. Bei der Variablenauflösung bin ich auf ein Drehbuch gestoßen, bei der meine Logik eine Variable nicht auflösen kann...
Script: scripttemplate-random-ron-fightagainst01, Variable "ROLENAME1" aus der Beschreibung.

Ist das ein Fehler in der Datenbank?

**Comment by GWRon** [comment]
rolename wird von der Spiellogik bereitgestellt.

game.production.script.bmx
-> Method _ReplacePlaceholders:TLocalizedString(text:TLocalizedString)

```
Case "ROLENAME1", "ROLENAME2", "ROLENAME3", "ROLENAME4", "ROLENAME5", "ROLENAME6", "ROLENAME7"
Case "ROLE1", "ROLE2", "ROLE3", "ROLE4", "ROLE5", "ROLE6", "ROLE7"
Case "GENRE"
Case "EPISODES"
```
(episodes liefert derzeit faelschlich noch das genre zurueck ...)

**Comment by GWRon** [comment]
Neben diesen gibt es noch "ReplaceTextWithGameInformation()" - was erlaubt, "gameinformation"-Werte abzurufen (game.gameinformation.base.bmx).

Derzeit sind "game.gameinformation.bmx"-Infoprovider die einzig genutzten.

stationmap:countryname
stationmap:population
...
oder 
worldtime:weekday
worldtime:germancurrency (hier wegen DM und Euro)

**Comment by GWRon** [comment]
der gameinformationprovider ist auch dazu da, anonym auf bestimmte Informationen zugreifen zu koennen (ohne eine zyklische Abhaengigkeit zu entwickeln  - also A importiert B, B importiert A)

**Comment by nittka** [comment]
Danke, das war sehr hilfreich. Da habe ich auch gleicht gemerkt, dass mein Pattern für die Erkennung von Variablen noch nicht passte...

**Comment by nittka** [comment]
Dokumentation ist angepasst. Die Umsetzung im Editor erfolgt im allgemeinen Ausbau von Validierung, Autovervollständigung etc.
