### ISSUE TITLE
Hervorheben/Markieren von Echten/Fake-Personen

### ISSUE THREAD

**Issue by GWRon** [TVTower/TVTDatabaseEditor#16]
In Drop-Downs die Unterschiede zwischen Echt/Fake hervorheben/markieren.

**Comment by nittka** [comment]
Ich gehe aktuell davon aus, dass eine Person echt ist, wenn das Fictional-Flag fehlt oder den Wert 0 hat. Im Umkehrschluss eine ausgedachte Person muss das Flag gesetz haben. (Zumindest wird das Flag bei TPersonBase#New nicht gesetzt.)
(Das bedeutet übrigens dass ein Großteil der insignificants von rumpelfreddy reale Personen wären. Geschlecht, Land, Fictional fehlt)

Wenn Du eine gute Idee für ein Icon zur Unterscheidung echt/unecht hast, lass es mich wissen.

**Comment by GWRon** [comment]
Ja, der "default" ist "Real" (damit nicht ausversehen jemand reales "reinflutscht"). Wenn das bei Rumpelfreddy fehlt - ja hab ich auch gerade gesehen, die muesste man wohl nachtragen.

Icons: entweder simpel ein "R/F" in Fettschrift - oder ein icon wie die Bildersuche nach "disguise icon" ergibt... fuer "fake"
