### ISSUE TITLE
Run Konfiguration verfügbar machen: Mehr als ein Eintrag für 'Generate Database' und 'Launch Runtime Eclipse'

### ISSUE THREAD

**Issue by jukey** [TVTower/TVTDatabaseEditor#2]
Ich bin den Schritten in der readme gefolgt, bis zu folgender Stelle:

> **Run-Konfigurationen verfügbar machen**
> * In der Eclipse-Toolbar unter den Hauptmenüpunkten sollte ein Bereich mit einem "Bug" und 3 verschiedenen grünen "Play"-Icons sein; das sind die verschiedenen Debug und Run-Varianten.
> * Auf den Pfeil(!) nach unten neben dem "Play" ganz links (`Run`) klicken
> * Es sollte ein Menü aufgehen, den Punkt `Organize Favorites...` auswählen
> * Im Dialog `Organize Run Favorites` die Aktion `Add...` auswählen und jeweils einen Eintrag `Generate Database...` und `Launce Runtime Eclipse` selektieren und mit `OK` abschließen

Ich sehe aus irgend einem Grund zweimal 'Generate Database' und 'Launch Runtime Eclipse':
![image](https://user-images.githubusercontent.com/295928/114243845-9f7add80-998d-11eb-8a75-3e8f0e5d282d.png)

Wähle ich jetzt alle vier Einträge oder die jeweils ersten/zweiten?

**Comment by nittka** [comment]
Deshalb steht (unauffällig) in der Anleitung "jeweils einen". Es spielt keine Rolle, welchen der beiden.
(Es gibt jede nur einmal - sie liegen aber in einem Projekt, dass Unterordner eines anderen Projekts ist. Eclipse findet sie also zweimal.)

**Comment by jukey** [comment]
Wer lesen kann ist klar im Vorteil. Danke! :)
