### ISSUE TITLE
Editor / Validator chokes when the description texts contain some XML keywords

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTDatabaseEditor#21]
![Screenshot from 2024-06-09 18-51-44](https://github.com/TVTower/TVTDatabaseEditor/assets/123826268/31116b96-661f-4a26-91d5-2556affb3014)

Here, a description contains the word "creator", which causes a lot of erroneous "consecutive" errors. Replacing the word "creator" or removing it makes them go away. Other word it doesn't seem to like is "job". Guess the parser is too "greedy".

**Comment by nittka** [comment]
The structure of the grammar and the parsing process require all valid keywords to be explicitly enumerated for title/description etc. I have not done that systematically.
However, "job" should not be a problem. In which xml tag did get an error?

**Comment by scr0llbaer9000** [comment]
Wow that is weird haha.

Ok "job" was not the problem, but "achievement" definitely was another. I think that is all I have for now.

**Comment by nittka** [comment]
Once, the script template target group syntax is agreed on, I will update the documentation and provide an updated editor version which fixes these issues as well.

**Comment by nittka** [comment]
Documentation and editor have been updated.

**Comment by scr0llbaer9000** [comment]
[Programmes](https://github.com/TVTower/Documentation/blob/master/database_de/programmes.md) in der Doku hat unter "Ziel- und Lobbygruppen (groups)" immer noch die "target_groups_optional" drin.

**Comment by nittka** [comment]
... Bei der Korrektur war ich wohl zu sehr auf die Drehbuchvorlagen konzentiert. Zeile ist nun gelöscht.

**Comment by scr0llbaer9000** [comment]
some more keywords it doesn't like: one or more of "blocks", "review", "potential". (had all these in a single item.)

**Comment by nittka** [comment]
Cannot reproduce blocks/potential - review is problematic, though.

(Please do not add new issues to a closed ticket as they may be overlooked. Open a new ticket.)
