### ISSUE TITLE
The application could not start (Schritt: Runtime-Eclipse starten)

### ISSUE THREAD

**Issue by jukey** [TVTower/TVTDatabaseEditor#3]
Ich bin den Schritten in der readme bis zu dieser Stelle gefolgt:

> ## Runtime-Eclipse starten
> 
> Um den Editor in Aktion zu sehen, wird ein Runtime-Eclipse gestartet, in dem dann der Editor verfügbar ist.
> In der `Run`-Aktion den Punkt `Launch Runtime Eclipse` anklicken.

Wenn ich diesen Punkt auswähle erscheint folgende Fehlermeldung:

![image](https://user-images.githubusercontent.com/295928/114264022-c87c8c00-99e8-11eb-84c1-09917b3ac101.png)

Das genannte log sieht dann wie folgt aus:

- [eclipse-error.log](https://github.com/TVTower/TVTDatabaseEditor/files/6289524/eclipse-error.log)

**Comment by nittka** [comment]
Ich habe bei mir aktuell noch die Eclipse-Version 2020-09 am Laufen. Diese habe ich auch beim Nachstellen der Anleitung verwendet. Ich versuche es auch nochmal mit der aktuellen.
Du hast aber die Java-Edition verwendet? Und es gab nach dem Generierungsschritt keine Fehler in den Projekten?

Bei der Editor-Entwicklung bin in mit Windows unterwegs. Wenn er SWT nicht findet, könnte es aber auch sein, dass die Launch-Konfiguration nicht plattform-unabhängig ist.

Im Run-Aktions-Menü gibt es auch den Punkt "Run Configurations...". Dort kannst Du die "Launch Runtime Eclipe"-Konfiguration auch anschauen und editieren (ist wieder zweimal da, nimm die erste).

Probiere mal folgendes:
* Selektiere die Run-Konfiguration
* Ändere im Reiter "Plug-ins" im Drop-Down "Launch with" den Wert auf "pluigins selected below only"
* In dem großen Feld darunter sollten nun viele Plugins erscheinen und alle sind selektiert
* Entferne die Markierung bei den "workspace" plugins - nur die Target Platform-Plugins sollten nun markiert sein
Nach Apply und Run sollte das Runtime-Eclipse starten. Ich vermute, es kommt derselbe Fehler, was darauf hindeuten würde, dass die Target-Platform "fehlerhaft" ist.

Das müsste ich dann bei mir weiter untersuchen.

Folgende zweite Variante für das Testen gibt es noch:

Im Projekt "org.tvtower.db.parent" gibt es eine "pom.xml". Falls bei Rechtsklick "Run As"->"Maven install" der Build-Lauf erfolgreich durchgeht (falls nicht - auch Bescheid sagen), befinden sich anschließend im Projekt "org.tvtower.db.repository" im Verzeichnis target/repository/plugins die benötigten jar-Dateien.

Im Startverzeichnis des Eclipse gibt es einen Ordner "dropins". Kopiere alle jars, die nicht "source_" im Namen haben ("...db_...", "...db.ide_...", "...db.ui_...") in den Dropins-Ordner. Wenn Du dann das Eclipse neustartest, sollte der Editor bereits "im ersten" Eclipse verfügbar sein.
Du importierst dann das TVT-Repo hier analog der Beschreibung für das Runtime-Eclipse.

**Comment by nittka** [comment]
Ich habe gerade gesehen, dass die Launch-Konfiguration Windows-spezifische Plugins referenziert. Ich muss mal schauen, ob es funktioniert, diese rauszuwerfen.

**Comment by nittka** [comment]
Also Variante 3 zum Probieren:
Im Projekt "org.tvtower.db" im Ordner ".launch" Die Datei "Launch Runtime Eclipse.launch" im Texteditor öffnen und all Zeilen in denen "win" vorkommt löschen.

Dann wie oben beschrieben unter "Run Configurations" die Konfigruation öffnen und im Reiter "Pluigins" rechts den Button "Add Required Plugins" anklicken und dann speichern und starten.

Diese Rückmeldung zeigt mir, dass ich die Launch-Konfiguration für das Runtime-Eclipse nicht mit ausliefern sollte - das bereitet mehr Probleme als es hilft.

**Comment by GWRon** [comment]
Ja, so started die neue Eclipse-Instanz ("Runtime").

![image](https://user-images.githubusercontent.com/2625226/114266804-92470880-99f8-11eb-9c87-754b535c7c6c.png)
(.log ist wohl noch vom letzten Fehler gefuellt - trotz IDE-Neustart)

**Comment by jukey** [comment]
Also ich scheitere nach wie vor und bin ein wenig lost. Du sprachst von einem Discord-Server, @nittka? Dort müsste ich doch auch meinen Bildschirm freigeben können, so dass du mir direkt helfen könntest. Falls du magst könnten wir morgen Abend mal scheuen, woran es liegt, dass ich nicht weiter komme. Alternativ können wir auch https://meet.jit.si/ nutzen.

**Comment by GWRon** [comment]
Der discord channel sollte bei tvtower.org verlinkt sein.

Ich habe den editor nach der "add required plugins"-interaktion nutzen koennen. Wenn auch einfach nur als intelligenterer XML-Editor.

**Comment by nittka** [comment]
Bezüglich TVTower bin ich nur hier bei Github aktiv (Discord gar nicht). Support via jit.si wäre aber problemlos möglich. Ich kläre das heute mal und schicke einen Raum und Zeitvorschlag per Mail.

(Aktuell ist der Editor noch gar nicht so intelligent, sondern kennt nur die Struktur - auch keine Wertebereiche. Die ganzen interessanten Features kommen erst noch.)

**Comment by nittka** [comment]
> Alternativ können wir auch https://meet.jit.si/ nutzen.

Mail mit Terminvorschlägen ist raus, falls sie nicht angekommen ist, bitte nochmal melden.

**Comment by jukey** [comment]
> Der discord channel sollte bei tvtower.org verlinkt sein.
> 
> Ich habe den editor nach der "add required plugins"-interaktion nutzen koennen. Wenn auch einfach nur als intelligenterer XML-Editor.

Ich habe den discord Server auch nach längeren Suchen auf der Seite und googeln nicht entdecken können.

**Comment by jukey** [comment]
Dank des Video-Call funktioniert es jetzt auch bei mir. Vielen Dank für die Hilfe und Erläuterungen.

**Comment by GWRon** [comment]
https://discord.gg/SrC8YyJs


Damit sollte es gehen
