### ISSUE TITLE
flags in News-Effect

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTDatabaseEditor#6]
Aktuell kommt das "flags"-Attribut im Effekt-Knoten von Nachrichten genau einmal vor. (jorgaeff.xml news-id news-jorgaeff-1985-2-02a).
Ich vermute, dass das copy/paste-Fehler ist, denn die flags können ja direkt in den referenzierten Nachrichten gesetzt werden. Ich würde diese flags gern entfernen. Der Code für das Übernehmen von Effekt-Daten ist aber so generisch, dass schwer rauszufinden ist, welche Felder überhaupt erlaubt sind und was ihre Wirkung ist.

Erste und wichtigste Frage also: kann ich "flags" als Eigenschaft von Effekt als nicht unterstützt betrachten?

**Comment by GWRon** [comment]
Ja der ist sehr generisch gehalten..und die Effekte (Typen) koennen selbst bestimmen, was so "gebraucht" wird.

Wenn der entsprechende Effekt nie auf "flags" zugreift, kann das Attribut dort auch weg.

Kann aber gern nochmal genauer nachschauen, wenn ich am PC bin.

**Comment by nittka** [comment]
Ja, das wäre nett. Ziel ist ja, zu dokumentieren was geht und was gebraucht wird. Bei vielen Eigenschaften kommt man mit Volltextsuche ziemlich weit, aber "flags"... Und in der Konstantenklasse habe ich auch nichts passendes gefunden. Für andere Flags gibt es da ja einen Eintrag, aber für Effekt habe ich nichts gefunden.

**Comment by nittka** [comment]
Nach dem Datenbankaufräumen, werden Effekt-Flags nicht verwendet und sind auch noch nicht in der Dokumentation. Wären es die Flags aus TGameModifierBase (permanent, activated etc. ab Zeile 219 in game.modifier.base.bmx)?
Gibt es Anwendungsfälle, in denen man eins dieser Flags in der Datenbank explizit setzen wollen würde oder sind die eigentlich nur für die interne Ablaufsteuerung gedacht?

**Comment by GWRon** [comment]
Ich denke, die Flags ind TGameModifierBase sind eher "intern".

Entsprechend koennte das aus der DB wohl "weg".

**Comment by nittka** [comment]
OK. Das Entfernen aus dem Datenbankcode müsste man noch machen.
