### ISSUE TITLE
programrole vs celebrity vs insignificant

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTDatabaseEditor#7]
Kannst Du ganz kurz die Unterschiede zwischen den 3 Personentypen beschreiben? (Welche Gruppe wird für welche Zwecke im Spiel verwendet. Und insb. aus welcher Gruppe kommen die möglichen Kandidaten im Supermarkt.)
Von den in programroles definierten Personen wird nur eine einmal in der Datenbank referenziert (oder) und im Spiel sind sie mir auch noch nie aufgefallen.

**Comment by GWRon** [comment]
TProgrammeRole: Indiana Jones waere eine ProgrammeRole. 
Kurzum: es ermoeglich die "Wiedernutzung" einer bestimmten fiktiven Person (Jack Ryan, James Bond ...).
Derzeit hat das nicht wirklich Auswirkungen. Aber wird bspweise auch bei Drehbuechern genutzt - damit der Hauptdarsteller in einer Serie immer gleich heissen kann (ohne auf eine "Variable" zurueckzugreifen).

Insignificant: Person die als Laiendarsteller, -regisseur, -musikant ... eingesetzt wird. Besitz noch keine "Attribute" oder spezifische Biografie
Celebrity: Eine Person mit "Details" (Attributen, Geburtstdag, ...)

Urspruenglich wurden die beiden geschaffen um nicht unnoetig viel Daten bereitzuhalten ("Spart Platz")

**Comment by nittka** [comment]
Danke, das war hilfreich.
