### ISSUE TITLE
Property für echten Personennamen

### ISSUE THREAD

**Issue by nittka** [TVTower/TVTDatabaseEditor#8]
Aktuell gibt es zwei unterschiedliche Properties unter denen der echte Name einer Person angegeben werden kann: "real_last/first_name" und "last/first_name_original"

Ich würde das gern auf eine Variante reduzieren. Auch wenn es nur informativ ist. Im Code werden die "_original"-Varianten zumindest eingelesen und es wäre auch konsistent mit "title_original".

Spricht von Dir aus etwas dagegen, die andere Variante zu ersetzen?

**Comment by GWRon** [comment]
Da spricht absolut nix dagegen.

**Comment by nittka** [comment]
Schön.
